
# yaml-language-server: $schema=./values.root.schema.json

global:
  domain: <DOMAIN>
  imagePullSecret: {}
srv:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    messaging:
      serviceInstanceName: event-mesh
  image:
    repository: <DOCKER_ACCOUNT>/kyma-cap-s4ems-srv
    tag: latest
  env:
    SERVERLESS_URL: https://<RELEASE_NAME>-qrcodegenerator.<domain>
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1000M
    requests:
      cpu: 1000m
      ephemeral-storage: 1G
      memory: 1000M
  health:
    liveness:
      path: /
    readiness:
      path: /
  additionalVolumes:
    - name: connectivity-secret
      volumeMount:
        mountPath: /bindings/connectivity
        readOnly: true
      projected:
        sources:
          - secret:
              name: <CONNECTIVITY_SECRET>
              optional: false
          - secret:
              name: <CONNECTIVITY_SECRET>
              optional: false
              items:
                - key: token_service_url
                  path: url
          - configMap:
              name: "{{ .Release.Name }}-connectivity-proxy-info"
              optional: false
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: kyma-cap-s4ems
    tenant-mode: dedicated
hana-deployer:
  image:
    repository: <DOCKER_ACCOUNT>/kyma-cap-s4ems-db
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
event-mesh:
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: com.bp.businesspartners
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
  image:
    repository: <DOCKER_ACCOUNT>/kyma-cap-s4ems-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
backendDestinations:
  srv-binding:
    service: srv

gitusername: <base64_encodeduser>
gitpassword: <base_64_encoded_GIT_secret>
giturl: <git_repo_url>
gitbranch: <git_branch>
  
functionshttpproxy: https://connectivity-proxy.kyma-system.svc.cluster.local:20003
functionsenv: '{ "name":"s4h", "attachmentSrvApi":"API_CV_ATTACHMENT_SRV", "businessPartnerSrvApi":"API_BUSINESS_PARTNER", "businessObjectTypeName" : "BUS1006" }'